# Generated by Django 2.2.28 on 2024-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchesentry',
            name='team1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='team2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='umpire1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='umpire2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='umpire3',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='venue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matchesentry',
            name='winner',
            field=models.CharField(max_length=100),
        ),
    ]
